mod_player:
    rename:
        activate: true
        price: 2000
        devise: 1
    delete:
        activate: true
    repairPosition:
        activate: true
        
register:
    activate: true
    emailActivation: true
    initCash: 0
    initMileage: 0
 
item_shop:
     activate: true
 
marche:
     activate: true
     
support:
    max_open: 3