mod_player:
    rename:
        activate: true
        price: 2000
        devise: 1
    delete:
        activate: true
    repairPosition:
        activate: true
        
register:
    activate: true
    emailActivation: true
    initCash: 0
    initMileage: 0
 
item_shop:
     activate: true
     rechargement:
         activate: true
         hipay:
             activate:      true
             apiBaseUrl:    https://api.allopass.com/rest
             apiKey:        2955bb0ffd36a187359fb3f51ecb7904
             apiSecretKey:  ff014ce9b93f163b73660bf09f629bcf
             siteId:        330033
             productId:     1449149
             cash:          1350
             devise:        1
         paypal:
            activate: true
            devise: 1
            hostedButtonId: RX9W8ULCKZ3HY
             
 
marche:
     activate: true
     
support:
    max_open: 3