baseURL: https://vamosmt2.local/
gameVersion: 5.1.9
requiredSSL: true
linkClient: http://vamosmt2.org:81/Installateur%20VamosMT2%20Client%20officiel%202014-2015.exe
linkClientTorrent: http://vamosmt2.org:81/VamosMT2%20Client%20officiel%202014-2015.exe.torrent

manualActivation: true
defaultCash: 0
defaultMileage: 0

libelleCash: VamoNaies
libelleMileage: TanaNaies

libelleEmpire1: Shinsoo
libelleEmpire2: Chunjo
libelleEmpire3: Jinno

twigCache: false
twigCacheUrl: /cache/twig

bdd:
    cache: array
    driver: mysql
    host: localhost
    user: root
    password: ~
    port: 3306
    charset: UTF8

smtp:
    host: localhost
    port: 25
    user: ~
    password: ~
    sender: no-reply@vamosmt2.org
    replyTo: contact@vamosmt2.org

encryptKey: vamoslelapin

fastChatType: files

itemShopReloadCash: 1350

ipTestServer: 94.23.6.155
portTestServer: 3306

templateMod: default #christmas