imports:
    - { resource: language.yml }

baseURL: https://vamosmt2.local/
gameVersion: 5.1.9
requiredSSL: true
encryptKey: vamoslelapin

linkClient: http://vamosmt2.org:81/Installateur%20VamosMT2%20Client%20officiel%202014-2015.exe
linkClientTorrent: http://vamosmt2.org:81/VamosMT2%20Client%20officiel%202014-2015.exe.torrent

templateMod: default #christmas

register:
    emailActivation: true
    initCash: 0
    initMileage: 0

twigCache: false
twigCacheUrl: /cache/twig

bdd:
    cache: array
    driver: mysql
    host: localhost
    user: root
    password: ~
    port: 3306
    charset: UTF8

smtp:
    host: localhost
    port: 25
    user: ~
    password: ~
    sender: no-reply@vamosmt2.org
    replyTo: contact@vamosmt2.org

serverStatus:
    host: 94.23.6.155
    port: 3306

fastChatType: files
itemShopReloadCash: 1350