<?php

$Array_Poisson = array(
    '0' => 'Rien',
    '1' => 'Anneau d\'or',
    '2' => 'Petit Poisson',
    '3' => 'Sandre',
    '4' => 'Poisson Mandarin',
    '5' => 'Gros Sandre',
    '6' => 'Carpe',
    '7' => 'Saumon',
    '8' => 'Carpe Amours',
    '9' => 'Truite de Ruisseau',
    '10' => 'Inconnu',
    '11' => 'Truite Arc-en-Ciel',
    '12' => 'Inconnu',
    '13' => 'Inconnu',
    '14' => 'Perche',
    '15' => 'Inconnu',
    '16' => 'Poisson-Chat',
    '17' => 'Inconnu',
    '18' => 'Inconnu',
    '19' => 'Inconnu',
    '20' => 'Inconnu',
    '21' => 'Inconnu',
    '22' => 'Inconnu',
    '23' => 'Inconnu',
    '24' => 'Inconnu',
    '25' => 'Inconnu',
    '26' => 'Inconnu',
    '27' => 'Inconnu',
    '28' => 'Inconnu',
    '29' => 'Inconnu',
    '30' => 'Inconnu',
    '31' => 'Inconnu',
    '32' => 'Symbole du Roi Sage',
    '33' => 'Gants du Roi Sage'
);

$Array_Poisson_Materiel = array(
    '20' => 'Canne à Pêche +1/Pâte',
    '30' => 'Canne +1/Vers | Canne +2/Pâte',
    '50' => 'Canne +1/Petit Pois. | Canne +3/Vers',
    '40' => 'Canne +2/Vers | Canne +3/Pâte',
    '50' => 'Canne +1/Petit Pois. | Canne +3/Vers | Canne +4/Pâte',
    '60' => 'Canne +2/Petit Pois. | Canne +4/Vers | Canne +5/Pâte',
    '70' => 'Canne +3/Petit Pois. | Canne +5/Vers | Canne +6/Pâte',
    '80' => 'Canne +4/Petit Pois. | Canne +6/Vers | Canne +7/Pâte',
    '90' => 'Canne +5/Petit Pois. | Canne +7/Vers | Canne +8/Pâte',
    '100' => 'Canne +6/Petit Pois. | Canne +8/Vers | Canne +9/Pâte',
    '110' => 'Canne +7/Petit Pois. | Canne +9/Vers | Canne +10/Pâte',
    '120' => 'Canne +8/Petit Pois. | Canne +10/Vers | Canne +11/Pâte',
    '130' => 'Canne +9/Petit Pois. | Canne +11/Vers | Canne +12/Pâte',
    '140' => 'Canne +10/Petit Pois. | Canne +12/Vers | Canne +13/Pâte',
    '150' => 'Canne +11/Petit Pois. | Canne +13/Vers | Canne +14/Pâte',
    '160' => 'Canne +12/Petit Pois. | Canne +14/Vers | Canne +15/Pâte',
    '170' => 'Canne +13/Petit Pois. | Canne +15/Vers | Canne +16/Pâte',
    '180' => 'Canne +14/Petit Pois. | Canne +16/Vers | Canne +17/Pâte',
    '190' => 'Canne +15/Petit Pois. | Canne +17/Vers | Canne +18/Pâte',
    '200' => 'Canne +16/Petit Pois. | Canne +18/Vers | Canne +19/Pâte',
    '210' => 'Canne +17/Petit Pois. | Canne +19/Vers | Canne +20/Pâte',
    '220' => 'Canne +18/Petit Pois. | Canne +20/Vers',
    '230' => 'Canne +19/Petit Pois.',
    '240' => 'Canne +20/Petit Pois.'
);

$Bonus_Item = array(
    '0' => '',
    '1' => 'Max PV',
    '2' => 'Max PM',
    '3' => 'Vitalité',
    '4' => 'Intelligence',
    '5' => 'Force',
    '6' => 'Dexterité',
    '7' => 'Vitesse d\'attaque',
    '8' => 'Vitesse de d&eacute;placement',
    '9' => 'Vitesse des sorts',
    '10' => 'Régénération des PV',
    '11' => 'Régénération des PM',
    '12' => 'Chance d\'empoisonnement ',
    '13' => 'Chance de Stunt',
    '14' => 'Chance de ralentissement',
    '15' => 'Chance de faire un Coup Critique',
    '16' => 'Chance de faire un Coups Perçant',
    '17' => 'Force contre les demi-hommes',
    '18' => 'Force contre les animaux',
    '19' => 'Force contre les Orcs',
    '20' => 'Force contre ésotérique',
    '21' => 'Force contre les morts-vivants',
    '22' => 'Force contre les D&eacute;mons',
    '23' => 'Dégats absorbés par les PV',
    '24' => 'Dégats absorbés par les PM',
    '25' => 'Chance de prendre les PM de l\'adversaire',
    '26' => 'Chance de r&eacute;cup&eacute;ration des PM',
    '27' => 'Chance de bloquer une attaque physique',
    '28' => 'Chance d\'éviter les flèches',
    '29' => 'Défense a L\'Epee',
    '30' => 'Défense Epee a deux mains',
    '31' => 'Défense a la Dague',
    '32' => 'Défense au Gong',
    '33' => 'Résistance aux Spécialistes',
    '34' => 'Résistance aux Flèches',
    '35' => 'Résistance au Feu',
    '36' => 'Résistance à la Lumière',
    '37' => 'Résistance à la Magie',
    '38' => 'Résistance au Vent',
    '39' => 'Chances de détourner une attaque physique',
    '40' => 'Chance de détourner une Malédiction',
    '41' => 'Résistance contre le Poison',
    '42' => 'Chances de restaurer les PM',
    '43' => 'Chances d\'avoir un Bonus XP',
    '44' => 'Chances de Double Yangs',
    '45' => 'Chances de dropper le double d\'objets',
    '46' => 'Trank effekt zuwachs',
    '47' => 'Chance TP wiederherrzustellen',
    '48' => 'Anti-stunt',
    '49' => 'Anti-ralentissement',
    '50' => 'Imun gegen Stürzen',
    '52' => 'Bogenreichweite +',
    '53' => 'Valeur d\'attaque +',
    '54' => 'Point de défense +',
    '55' => 'Magischer AW',
    '56' => 'Magische Verteidigung',
    '58' => 'Max. Ausdauer',
    '59' => 'Bonus contre les Guerriers',
    '60' => 'Bonus contre les Ninjas',
    '61' => 'Bonus contre les Suras',
    '62' => 'Bonus contre les Shamans',
    '63' => 'Bonus contre les Monstres',
    '64' => 'Angriffswert +?',
    '65' => 'Verteidigung',
    '66' => 'EXP +?%',
    '67' => 'Dropchance [Gegenstände]',
    '68' => 'Dropchance [Gold]',
    '71' => 'Degats de Compétences',
    '72' => 'Degats Moyens',
    '73' => 'Widerstand gegen Fertigkeitsschaden',
    '74' => 'durchschn. Schadenswiderstand',
    '76' => 'iCafe exp-bonus',
    '77' => 'iCafe Chance auf erbeuten von gegenständen',
    '78' => 'Chances de bloquer une attaque Guerrier',
    '79' => 'Chances de bloquer une attaque Ninja',
    '80' => 'Chances de bloquer une attaque Sura',
    '81' => 'Chances de bloquer une attaque Shaman'
);

$Pierre_Item = array(
    '1' => '<img src=\'../images/pierres/Libre.png\' /><span style=\'position:relative; left:5px;\'>Libre</span>',
    '28960' => '<img src=\'../images/pierres/PierreBrisee.png\' /><span style=\'position:relative; left:5px;\'>Pierre Cassé</span>',
    '28030' => '<img src=\'../images/pierres/PierrePenetration.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Pénétration +0</span>',
    '28130' => '<img src=\'../images/pierres/PierrePenetration.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Pénétration +1</span>',
    '28230' => '<img src=\'../images/pierres/PierrePenetration.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Pénétration +2</span>',
    '28330' => '<img src=\'../images/pierres/PierrePenetration.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Pénétration +3</span>',
    '28430' => '<img src=\'../images/pierres/PierrePenetration.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Pénétration +4</span>',
    '28530' => '<img src=\'../images/pierres/PierrePenetration.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Pénétration +5</span>',
    '28630' => '<img src=\'../images/pierres/PierrePenetration.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Pénétration +6</span>',
    '81050' => '<img src=\'../images/pierres/PierrePenetration.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Pénétration +7</span>',
    '28031' => '<img src=\'../images/pierres/PierreSoufleMortel.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Souffle Mortel +0</span>',
    '28131' => '<img src=\'../images/pierres/PierreSoufleMortel.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Souffle Mortel +1</span>',
    '28231' => '<img src=\'../images/pierres/PierreSoufleMortel.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Souffle Mortel +2</span>',
    '28331' => '<img src=\'../images/pierres/PierreSoufleMortel.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Souffle Mortel +3</span>',
    '28431' => '<img src=\'../images/pierres/PierreSoufleMortel.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Souffle Mortel +4</span>',
    '28531' => '<img src=\'../images/pierres/PierreSoufleMortel.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Souffle Mortel +5</span>',
    '28631' => '<img src=\'../images/pierres/PierreSoufleMortel.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Souffle Mortel +6</span>',
    '81051' => '<img src=\'../images/pierres/PierreSoufleMortel.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Souffle Mortel +7</span>',
    '28032' => '<img src=\'../images/pierres/PierreApaisement.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Apaisement +0</span>',
    '28132' => '<img src=\'../images/pierres/PierreApaisement.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Apaisement +1</span>',
    '28232' => '<img src=\'../images/pierres/PierreApaisement.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Apaisement +2</span>',
    '28332' => '<img src=\'../images/pierres/PierreApaisement.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Apaisement +3</span>',
    '28432' => '<img src=\'../images/pierres/PierreApaisement.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Apaisement +4</span>',
    '28532' => '<img src=\'../images/pierres/PierreApaisement.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Apaisement +5</span>',
    '28632' => '<img src=\'../images/pierres/PierreApaisement.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Apaisement +6</span>',
    '81052' => '<img src=\'../images/pierres/PierreApaisement.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Apaisement +7</span>',
    '28033' => '<img src=\'../images/pierres/PierreAntiG.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Guerrier +0</span>',
    '28133' => '<img src=\'../images/pierres/PierreAntiG.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Guerrier +1</span>',
    '28233' => '<img src=\'../images/pierres/PierreAntiG.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Guerrier +2</span>',
    '28333' => '<img src=\'../images/pierres/PierreAntiG.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Guerrier +3</span>',
    '28433' => '<img src=\'../images/pierres/PierreAntiG.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Guerrier +4</span>',
    '28533' => '<img src=\'../images/pierres/PierreAntiG.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Guerrier +5</span>',
    '28633' => '<img src=\'../images/pierres/PierreAntiG.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Guerrier +6</span>',
    '28034' => '<img src=\'../images/pierres/PierreAntiN.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Ninja +0</span>',
    '28134' => '<img src=\'../images/pierres/PierreAntiN.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Ninja +1</span>',
    '28234' => '<img src=\'../images/pierres/PierreAntiN.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Ninja +2</span>',
    '28334' => '<img src=\'../images/pierres/PierreAntiN.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Ninja +3</span>',
    '28434' => '<img src=\'../images/pierres/PierreAntiN.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Ninja +4</span>',
    '28534' => '<img src=\'../images/pierres/PierreAntiN.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Ninja +5</span>',
    '28634' => '<img src=\'../images/pierres/PierreAntiN.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Ninja +6</span>',
    '28035' => '<img src=\'../images/pierres/PierreAntiS.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Sura +0</span>',
    '28135' => '<img src=\'../images/pierres/PierreAntiS.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Sura +1</span>',
    '28235' => '<img src=\'../images/pierres/PierreAntiS.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Sura +2</span>',
    '28335' => '<img src=\'../images/pierres/PierreAntiS.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Sura +3</span>',
    '28435' => '<img src=\'../images/pierres/PierreAntiS.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Sura +4</span>',
    '28535' => '<img src=\'../images/pierres/PierreAntiS.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Sura +5</span>',
    '28635' => '<img src=\'../images/pierres/PierreAntiS.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Sura +6</span>',
    '28036' => '<img src=\'../images/pierres/PierreantiSH.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Shaman +0</span>',
    '28136' => '<img src=\'../images/pierres/PierreantiSH.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Shaman +1</span>',
    '28236' => '<img src=\'../images/pierres/PierreantiSH.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Shaman +2</span>',
    '28336' => '<img src=\'../images/pierres/PierreantiSH.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Shaman +3</span>',
    '28436' => '<img src=\'../images/pierres/PierreantiSH.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Shaman +4</span>',
    '28536' => '<img src=\'../images/pierres/PierreantiSH.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Shaman +5</span>',
    '28636' => '<img src=\'../images/pierres/PierreantiSH.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Shaman +6</span>',
    '28037' => '<img src=\'../images/pierres/PierreAntiMobs.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Monstres +0</span>',
    '28137' => '<img src=\'../images/pierres/PierreAntiMobs.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Monstres +1</span>',
    '28237' => '<img src=\'../images/pierres/PierreAntiMobs.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Monstres +2</span>',
    '28337' => '<img src=\'../images/pierres/PierreAntiMobs.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Monstres +3</span>',
    '28437' => '<img src=\'../images/pierres/PierreAntiMobs.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Monstres +4</span>',
    '28537' => '<img src=\'../images/pierres/PierreAntiMobs.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Monstres +5</span>',
    '28637' => '<img src=\'../images/pierres/PierreAntiMobs.png\' /><span style=\'position:relative; left:5px;\'>Pierre Anti-Monstres +6</span>',
    '28038' => '<img src=\'../images/pierres/PierreEvasion.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Evasion +0</span>',
    '28138' => '<img src=\'../images/pierres/PierreEvasion.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Evasion +1</span>',
    '28238' => '<img src=\'../images/pierres/PierreEvasion.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Evasion +2</span>',
    '28338' => '<img src=\'../images/pierres/PierreEvasion.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Evasion +3</span>',
    '28438' => '<img src=\'../images/pierres/PierreEvasion.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Evasion +4</span>',
    '28538' => '<img src=\'../images/pierres/PierreEvasion.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Evasion +5</span>',
    '28638' => '<img src=\'../images/pierres/PierreEvasion.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Evasion +6</span>',
    '28039' => '<img src=\'../images/pierres/PierreEsquive.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Esquive +0</span>',
    '28139' => '<img src=\'../images/pierres/PierreEsquive.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Esquive +1</span>',
    '28239' => '<img src=\'../images/pierres/PierreEsquive.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Esquive +2</span>',
    '28339' => '<img src=\'../images/pierres/PierreEsquive.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Esquive +3</span>',
    '28439' => '<img src=\'../images/pierres/PierreEsquive.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Esquive +4</span>',
    '28539' => '<img src=\'../images/pierres/PierreEsquive.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Esquive +5</span>',
    '28639' => '<img src=\'../images/pierres/PierreEsquive.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Esquive +6</span>',
    '28040' => '<img src=\'../images/pierres/PierreMagie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Magie +0</span>',
    '28140' => '<img src=\'../images/pierres/PierreMagie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Magie +1</span>',
    '28240' => '<img src=\'../images/pierres/PierreMagie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Magie +2</span>',
    '28340' => '<img src=\'../images/pierres/PierreMagie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Magie +3</span>',
    '28440' => '<img src=\'../images/pierres/PierreMagie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Magie +4</span>',
    '28540' => '<img src=\'../images/pierres/PierreMagie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Magie +5</span>',
    '28640' => '<img src=\'../images/pierres/PierreMagie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Magie +6</span>',
    '28041' => '<img src=\'../images/pierres/PierreDeVie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Vie +0</span>',
    '28141' => '<img src=\'../images/pierres/PierreDeVie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Vie +1</span>',
    '28241' => '<img src=\'../images/pierres/PierreDeVie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Vie +2</span>',
    '28341' => '<img src=\'../images/pierres/PierreDeVie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Vie +3</span>',
    '28441' => '<img src=\'../images/pierres/PierreDeVie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Vie +4</span>',
    '28541' => '<img src=\'../images/pierres/PierreDeVie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Vie +5</span>',
    '28641' => '<img src=\'../images/pierres/PierreDeVie.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Vie +6</span>',
    '28042' => '<img src=\'../images/pierres/PierreDefense.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Défense +0</span>',
    '28142' => '<img src=\'../images/pierres/PierreDefense.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Défense +1</span>',
    '28242' => '<img src=\'../images/pierres/PierreDefense.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Défense +2</span>',
    '28342' => '<img src=\'../images/pierres/PierreDefense.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Défense +3</span>',
    '28442' => '<img src=\'../images/pierres/PierreDefense.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Défense +4</span>',
    '28542' => '<img src=\'../images/pierres/PierreDefense.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Défense +5</span>',
    '28642' => '<img src=\'../images/pierres/PierreDefense.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Défense +6</span>',
    '28043' => '<img src=\'../images/pierres/PierreHate.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Hâte +0</span>',
    '28143' => '<img src=\'../images/pierres/PierreHate.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Hâte +1</span>',
    '28243' => '<img src=\'../images/pierres/PierreHate.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Hâte +2</span>',
    '28343' => '<img src=\'../images/pierres/PierreHate.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Hâte +3</span>',
    '28443' => '<img src=\'../images/pierres/PierreHate.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Hâte +4</span>',
    '28543' => '<img src=\'../images/pierres/PierreHate.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Hâte +5</span>',
    '28643' => '<img src=\'../images/pierres/PierreHate.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Hâte +6</span>',
    '90102' => '<img src=\'../images/pierres/PierreForce.png\' /><span style=\'position:relative; left:5px;\'>Pierre de Force +7</span>',
    '90105' => '<img src=\'../images/pierres/PierreIntelligence.png\' /><span style=\'position:relative; left:5px;\'>Pierre d\'Intelligence +7</span>'
);